project:
  type: website

website:
  title: "Krishan Rajaratnam's blog"
  favicon: favicon.svg
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/krishanr
      - icon: twitter
        href: https://x.com/KrishanRajarat1
format:
  html:
    theme: cosmo
    css: styles.css



